### ISSUE TITLE
Design A Character Sheet Layout

### ISSUE THREAD

**Issue by sarah-johnson** [karst-club/karst#7]
More of the Character Sheet data should be stored in a structured format in yaml.

This issue is for designing the layout of the character sheet page, and also the structure of the yaml file that will hold the data.

This one is just for the design phase. There will be another issue for implementing the "charcter sheet layout" as a react component

**Comment by sarah-johnson** [comment]
What do we think about having an "equip" section on the sheet that's separate for items that would have slots for hands, armor, helmet and such?

**Comment by vonkow** [comment]
I had very intentionally shied away from dealing with equipping things beyond one and two-handed items but that was to keep the rules as written relatively simple. 

However, I'm totally for having an equipped items section on character sheets! I think most of the logic is straightforward (you have two hands, can't wear two hats at once, etc) aside from calculating if you are encumbered, which is currently implemented as a judgement call in the rules (aside: I should touch up those rules since they kinda conflict with / don't take into account armor weight classes).
